version: '3'

services:

  app:
    build: .
    container_name: conectepet
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:127.0.0.1"